# Site settings
author: Sara
title: My Data Science Journey
header-img: img/home-bg.png
email: sara.robinson27@gmail.com
copyright_name: Sara
description: > # this means to ignore newlines until "baseurl:"
  The Winding Road to Becoming a Data Scientist
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  srobz

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
